### ISSUE TITLE
Allow upstream volume to be auto-calculated from sum of downstream volumes

### ISSUE THREAD

**Issue by kias-git** [nowthis/sankeymatic#21]
Example flow

```
         3
12 <
         9
```

Here, if only 3 and 9 were specified, then sankeymatic calculates the 12.

**Comment by nowthis** [comment]
I'm not sure I follow - the Sankey algorithm from d3 already adds up all the inputs to a node to determine its total size.

Can you provide a sample SankeyMATIC input that doesn't work the way you want it to?

Example -- given:

    A [3] B
    A [9] C

the node A will automatically have size 12.

**Comment by chaos-git** [comment]
True.. but it only works for one level.

Consider this, I have a three level stream (grandparent, parent, child) and all I specify are the amounts that each child needs. It looks like this:

`
Grandparent [X] Parent1
Grandparent [Y] Parent2
Parent1 [2] Child1
Parent1 [4] Child2
Parent2 [6] Child3
Parent2 [8] Child4
`

Calculating the amount X and Y is not automated. I'd need to hardcode the amount in there and hence this is why I opened the feature request. I'd like to be able to specify a relationship between nodes without having to specify the amount and instead letting that amount be auto calculated. That would make this much more useful for budgeting purposes because then I could do a bottom up budget.

**Comment by nowthis** [comment]
Aha, I think I understand now.

So, it would be nice to have a syntax that lets you say 'this flow should adopt the size of the mentioned target node'. My first thought was, using a wildcard character (*) would make some sense:

```
Grandparent [*] Parent1
Grandparent [*] Parent2
Parent1 [2] Child1
Parent1 [4] Child2
Parent2 [6] Child3
Parent2 [8] Child4
```
However, that might be too simple --

I could easily see someone thinking a catch-all grand**child** node would be just as useful as a grandparent node, but if that is possible, then `[*]` will be ambiguous since using a simple wildcard character doesn't indicate direction (i.e. in this case, which node would adopt the volume of the other?):
```
node1 [*] node2
```
So maybe a directional hint would help:
```
node1 [<*] node2   ' node1 adopts node2's volume
node3 [*>] node4   ' node4 adopts node3's volume
```
So that would make the syntax for your example:
```
Grandparent [<*] Parent1
Grandparent [<*] Parent2
```
Does that seem like a viable/good-enough syntax?

I think that's a reasonable feature to add sometime. Unfortunately, I have several features queued up in front of it, so it may be a while. Patches are welcome, however.

**Comment by nowthis** [comment]
Good news - an auto-calculation syntax is now implemented:
* `[*]` = adopt any unused remainder from the source
* `[?]` = adopt any un-sourced amount from the target

So revising the example from above:
```
Grandparent [?] Parent1
Grandparent [?] Parent2
Parent1 [2] Child1
Parent1 [4] Child2
Parent2 [6] Child3
Parent2 [8] Child4
```

can now produce this output on the site:
![Example sankey diagram showing a Grandparent node of size 20 which was auto-calculated from the values of Parent1 (6) and Parent2 (14)](https://github.com/nowthis/sankeymatic/assets/5286645/f013f679-b492-4bda-aa7c-e165b1685247)

Here's a [public link with this diagram already loaded](https://sankeymatic.com/build/?i=OIJwhgdgJgDmIFMIBcAEBtA%2DAXVQBXiWQEYAoUSWQlDHfa5AJlIMRWI0dwGEALASwA2UMqyId0AFh4DhzMSkYYAbDKFQAzCwZL0ADjXDJpAM78AXglQB3VJIAM90qlS9UjR6QC28AOb8IVEFUYmYXEBCw1DRiPWdUACN3JwTfVABjAHtBTIiAYgAzIuL45HAIEzg2NAA5UghMqCtbUPi3DQBOADoAVnjKsHSAtL0yFwTcpoinF2ReBC8rBogEeKyc%2DL0t7fjMuCHkAE8Q0gKc23SAVxAANzBka6t7XviA%2BZB%2BZAKQTK9UZdWLnWuVQeQ64Ihu32n2Oz0kfUEYEOmUuaEmCAiYFRv3u%2DHS8QAVpcTMh%2BAVkR9%2DBVUHUXESSWTDkgoCYafFEDcMSYEL5wDA3LTUPdkIMBBAsl4YIIEMgECTMv8EIQSaREQkEIJWcD8o5dTNXPwmmyXAJfLxBPwzWhngB2PouAqZFAFQZWEyQEwAWm5HwK8QtKwGQwgaWeUUQiNJnLMlhCnhcPl8EEZcacao1EDAiyFMBgSpArIAmv0LFZQi8XNYEJbeGgHGmwOrBHdBJcrGBc%2Dmi%2DECpdBIIYIghmYnahiy4YJkzKTR2ACrKQPEqzW6550wOp59%2BLPsWALUnUPqTOl5tmschMj3%2BAW0OrHYh4glEGAANaTgJ10gttuoe8%2BNAAOQADRdAB8SDggBT8AAHqgAFgS4JiXEUMFwWBcwLAgmRFNyaBgKgHSPqgWhAoe8RQGRiwiqgiwoNuFSQC%2BCCHP%2BeJjv6%2DAMl4CR7pA6RymOQA) if anyone wants to play with it.

In addition:

Any time there are calculations to perform, SankeyMATIC will now add a **Console** section below the diagram which will log any calculation results in the order they were performed.

This can make it easier to trace complex calculations if they come out unexpectedly.

The console output for the above diagram looks like:

![Sample Console output with 2 lines: "Calculated: Grandparent ? Parent1 = 6" and "Calculated: Grandparent ? Parent2 = 14"](https://github.com/nowthis/sankeymatic/assets/5286645/bb0fb2a0-bb54-4d0e-9f1c-19dbb9a2c095)

**Comment by YeomansIII** [comment]
This is huge. Thank you so much for implementing this! I use SankeyMatic to make a monthly budget overview and this new features takes out all of the extra addition and subtraction that has to happen up the entire chain when I make a change to a category.

**Comment by kias-git** [comment]
Excellent! Thank you for persisting through
