### ISSUE TITLE
Not all input nodes show on diagram

### ISSUE THREAD

**Issue by Joeinca** [nowthis/sankeymatic#39]
Created my first Sankey chart with 8 input nodes and 12 output nodes.

Only 5 of the input nodes show on the chart.  I've changed order of input nodes. > Same output.

[List of Flows.xlsx](https://github.com/nowthis/sankeymatic/files/1943594/List.of.Flows.xlsx)

Thank you.

**Comment by nowthis** [comment]
Hi. I believe the issue is that some nodes flowing into the Budget have the same names as nodes receiving money from the Budget, and that kind of circular reference isn't handled by the algorithm.

One thing you can do is change the name of one side (or both), so the flows show as distinct items.

This is what that set of flows would look like, if I add ' Rev' to the left-side flows (where the name matches) and ' Exp' to the right-side:

```
Membership Rev [6101800] Budget
Fundraising Rev [4570000] Budget
Championship/Events Rev [4547600] Budget
Foundation Funding [2500000] Budget
USOC/ISU [993000] Budget
Program Revenue [683100] Budget
Publications/Magazine [187239] Budget
Other Revenue [101000] Budget

Budget [5321413] Championship/Events Exp
Budget [5090837] Operations
Budget [3379233] Athlete Programs
Budget [1826916] Membership Exp
Budget [782449] Synchronized Skating
Budget [639542] Publications
Budget [493063] Governance
Budget [385573] Other Expenses
Budget [364963] Grass Roots Development/ Adult Programs
Budget [345550] Fundraising Exp
Budget [303759] Technical Programs
Budget [135888] Collegiate Programs
```
This produces a full 21-node diagram (8 in, 1 in the middle, 12 out).

It has an imbalance, though, where $614,553 more is going into the Budget node than is coming out.
If there is no missing output line, you might add a line like this to help clarify that there was a surplus:
`Budget [614553] Surplus #0C0`
(The #0C0 syntax lets you set a specific color for the flow.)

**Comment by Joeinca** [comment]
Works like a charm.  Thanks
